# Generated by Django 4.1.3 on 2024-07-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.user')),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.score')),
            ],
        ),
        migrations.CreateModel(
            name='CircleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.circle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='CircleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.circle')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.profile')),
            ],
        ),
    ]
