# Generated by Django 4.1.3 on 2024-09-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_date',
            field=models.CharField(max_length=50),
        ),
    ]
