# Generated by Django 4.1.3 on 2024-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
