# Generated by Django 4.1.3 on 2024-07-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0002_rename_first_name_user_name_remove_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_impact', models.CharField(max_length=50)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.user')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethosapi.profile')),
            ],
        ),
    ]
