# Generated by Django 4.1.3 on 2024-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
