# Generated by Django 4.1.3 on 2024-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0005_log_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='event_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='log',
            name='log_date',
            field=models.DateField(auto_now=True),
        ),
    ]
