# Generated by Django 4.1.3 on 2024-07-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0006_log_event_date_log_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score_id',
        ),
    ]
