# Generated by Django 4.1.3 on 2024-08-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethosapi', '0007_remove_profile_score_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
